### ISSUE TITLE
Hands of the last boss

### ISSUE THREAD

**Issue by Aspirin18** [Harchvertelol/Dangerous-Dave-2-Modification-Edition#2]
The hands of the last boss appear by two pieces in each cycle. Thats why the boss has become harder. In the original, it was easier. In the Romero's version it was random. More often the only one hand appeared. And then the second one after 5-7 seconds or did not appear until the destruction of the hand.

**Comment by Harchvertelol** [comment]
Fixed. The fix will be in the next version (after v0.6).
