### ISSUE TITLE
What commands does console support?

### ISSUE THREAD

**Issue by necros2k7** [Harchvertelol/Dangerous-Dave-2-Modification-Edition#4]
subj

**Comment by Harchvertelol** [comment]
The console is used to develop and test any packages. In fact, you can enter cheats into it. In general, cheats can be found in the source code of the game. Are you sure you want to know them? This can make the game uninteresting. But of course I can say them :)

**Comment by necros2k7** [comment]
Thanx I`ll try to find myself at 1st.

**Comment by Harchvertelol** [comment]
Don't say them yet, am I getting it right? :) It's not hard to tell for me, I can say :)

**Comment by necros2k7** [comment]
OK you can say, just not enough time to check

**Comment by Harchvertelol** [comment]
AI on/off
level N
god on/off
ghost on/off (arrow, ctrl + arrow is fast speed, alt + arrow is slow speed, ctrl + alt + arrow is very fast speed)
